### ISSUE TITLE
compatibility with alfresco 5.2

### ISSUE THREAD

**Issue by mnesson** [atolcd/alfresco-event-scheduling#14]
Hello,

Have you planned to migrate this module to be compatible with Alfresco 5.2? If yes, do you have a date of availability?

Thanks in advance,
Regards,
NESSON Melvin

**Comment by bforest** [comment]
Hi,

Have you done some tests? (and read the README file? => https://github.com/atolcd/alfresco-event-scheduling/blob/master/README.md)
We have not tested but I think this module is already compatible with Alfresco 5.2.

Regards
