### ISSUE TITLE
How to change email template.

### ISSUE THREAD

**Issue by akashdubey251996** [atolcd/alfresco-event-scheduling#16]
Hi,
Its a very good add-on and very easy to use. I have implemented this i am receiving mail successfully . But i want to change the template of the mail notification how to do that.

I am using alfresco 5.2 community version. I hope i will get help.

**Comment by jberthoux** [comment]
Hi,

Thank you for installing the module.
The mail templates used by the module are deployed in the folder :  / Data dictionary / Scheduled Events / Email Templates:
* event_reminder_email.ftl
* event_created_email.ftl. 

You can edit the files "in line" or upload new versions. Changes will be automatically taken into account.

Regards,
Julien

**Comment by akashdubey251996** [comment]
Thanku so much Julien it works..

**Comment by jberthoux** [comment]
Hello,

Glad to hear that everything is working as expected.

Regards,
Julien
